<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'title',
		array(
			'name'=>'create_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'update_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'user_id',
			'value'=>$model->user->nickname,
		),
		'hits',
		array(
			'name'=>'sticky',
			'type'=>'boolean',
		),
		array(
			'name'=>'promote',
			'type'=>'boolean',
		),
		array(
			'name'=>'status',
			'value'=>$model->statusList[$model->status],
		),
		array(
			'name'=>'excerpt',
			'type'=>'raw',
		),
		array(
			'name'=>'content',
			'type'=>'raw',
		),
	),
)); ?>